export const RESTORE_TOKEN = 'RESTORE_TOKEN'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const RESET_SIGN_IN="RESET_SIGN_IN"

export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const RESET_SIGN_UP="RESET_SIGN_UP"

export const SIGN_OUT = 'SIGN_OUT'

export const CLIENT_TYPE_DRIVER = 'CLIENT_TYPE_DRIVER'
export const CLIENT_TYPE_CLIENT = 'CLIENT_TYPE_CLIENT'

export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_STRING = 'GET_LOCATION_STRING'
export const GET_LOCATION_SENDER = 'GET_LOCATION_SENDER'
export const GET_LOCATION_RECEIVER = 'GET_LOCATION_RECEIVER'
export const GET_SERVICE_TRANSPORT = 'GET_SERVICE_TRANSPORT'
export const GET_DISTANCE_MATRIX = "GET_DISTANCE_MATRIX"

export const CREATE_NEW_ORDER_TRANSPORT = "CREATE_NEW_ORDER_TRANSPORT"
export const RESET_LOCATION = "RESET_LOCATION"
